import Head from "next/head"
import { useState } from "react"
import {
  Box,
  Button,
  Flex,
  Heading,
  Input,
  Spacer,
  Text,
  useToast,
} from "@chakra-ui/react"

export default function Home() {
  // regular variables
  const toast = useToast()

  // useState
  const [toastTitle, setToastTitle] = useState("Title")
  const [toastMsg, setToastMsg] = useState("Message")
  const [firstState, setFirstState] = useState("first State")
  const [secondState, setSecondState] = useState("Click Me!")
  const [customHeader, setCustomHeader] = useState("Welcome!")

  // showToast is a function that draws a `Toast` on the screen when called
  function showToast() {
    toast({
      title: toastTitle,
      description: toastMsg,
      status: "success",
    })
  }

  function changeFirstState() {
    if (firstState === "first State") {
      setFirstState("second State")
    } else {
      setFirstState("first State")
    }
  }

  function changeSecondState() {
    if (secondState === "Click Me!") {
      setSecondState("You Clicked!")
    } else {
      setSecondState("Click Me!")
    }
  }

  function changeHeader() {
    if (customHeader === "Welcome!") {
      setCustomHeader("WoHo!")
    } else {
      setCustomHeader("Welcome!")
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* this is the Box (<div>) that defines the entire screen */}
      <Box maxW="full" maxH="100vh" align="center">
        {/* This is the Heading (<h1>) */}
        <Heading pt="20">{customHeader}</Heading>

        <Heading size="md" pt="10">
          Toast Example
        </Heading>
        <Box
          borderColor="green.100"
          borderWidth="1px"
          borderRadius="xl"
          w="55%"
          p="3"
        >
          {/* No input */}
          <Flex>
            <Spacer />
            <Button colorScheme="purple" onClick={() => showToast()}>
              Show Toast
            </Button>
          </Flex>

          {/* Message input */}
          <Flex pt="5">
            <Input
              borderColor="whatsapp.200"
              placeholder="Write the text you want the toast to display"
              onChange={(e) => setToastMsg(e.target.value)}
            />
            <Button colorScheme="whatsapp" onClick={() => showToast()}>
              Show Toast
            </Button>
          </Flex>

          {/* Title and Message inputs */}
          <Flex pt="5">
            <Input
              borderColor="teal.200"
              maxW="45%"
              placeholder="Write the text you want the toast 'Title' to display"
              onChange={(e) => setToastTitle(e.target.value)}
            />
            <Input
              borderColor="purple.100"
              maxW="45%"
              placeholder="Write the text you want the toast 'Message' to display"
              onChange={(e) => setToastMsg(e.target.value)}
            />
            <Button colorScheme="teal" onClick={() => showToast()}>
              Show Toast
            </Button>
          </Flex>
        </Box>

        {/* Simple example of what useState can do */}
        <Heading size="md" mt="5">
          State Example
        </Heading>
        <Box
          borderColor="blue.100"
          borderWidth="1px"
          borderRadius="xl"
          w="55%"
          p="3"
        >
          {/* Change state to update text and text color */}
          <Flex align="center" justify="space-evenly">
            <Flex
              maxW="60%"
              mt="20"
              align={"center"}
              justify={"space-between"}
              flexDir={"column"}
            >
              <Text
                textColor={
                  firstState === "first State" ? "green.500" : "red.500"
                }
              >
                {firstState}
              </Text>
              <Button onClick={changeFirstState}>Change State</Button>
            </Flex>

            {/* Change state to update text on a button and color of the button */}
            <Flex
              maxW="60%"
              mt="20"
              align={"center"}
              justify={"space-between"}
              flexDir={"column"}
            >
              <Button
                colorScheme={secondState === "Click Me!" ? "orange" : "cyan"}
                onClick={changeSecondState}
              >
                {secondState}
              </Button>
            </Flex>

            {/* Change state to update Heading for the page */}
            <Flex
              maxW="60%"
              mt="20"
              align={"center"}
              justify={"space-between"}
              flexDir={"column"}
            >
              <Button onClick={changeHeader}>Change Header</Button>
            </Flex>
          </Flex>
        </Box>
      </Box>
    </>
  )
}
